export default [
  {
    id: 1,
    spz: 'BA458CD',
    img: '../img/01fabiaGreen.png',
    znacka: 'skoda',
    model: 'fabia II',
    farba: 'zelena',
    palivo: 'LPG',
    vykon: 88,
    spotreba: 7,
    znamka: true,
    pozicane: false,
    cena: 59,
    popis:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce ipsum nunc, dictum vel dapibus at, luctus sit amet diam. Nam.',
  },
  {
    id: 2,
    spz: 'BA985CZ',
    img: '../img/02golf mk53.png',
    znacka: 'volkswagen',
    model: 'golf mk5',
    farba: 'modra',
    palivo: 'diesel',
    vykon: 130,
    spotreba: 9,
    znamka: true,
    pozicane: false,
    cena: 60,
    popis:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce ipsum nunc, dictum vel dapibus at, luctus sit amet diam. Nam.',
  },
  {
    id: 3,
    spz: 'BA333DO',
    img: '../img/03hyundai i30.png',
    znacka: 'hyundai',
    model: 'i30',
    farba: 'tyrkysova',
    palivo: 'benzin',
    vykon: 90,
    spotreba: 6,
    znamka: false,
    pozicane: false,
    cena: 48,
    popis:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce ipsum nunc, dictum vel dapibus at, luctus sit amet diam. Nam.',
  },
  {
    id: 4,
    spz: 'ZA478RD',
    img: '../img/04kia ceed.png',
    znacka: 'kia',
    model: 'ceed',
    farba: 'cierna',
    palivo: 'benzin',
    vykon: 90,
    spotreba: 6,
    znamka: false,
    pozicane: false,
    cena: 64,
    popis:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce ipsum nunc, dictum vel dapibus at, luctus sit amet diam. Nam.',
  },
  {
    id: 5,
    spz: 'ZA159BN',
    img: '../img/05octaviaRS.png',
    znacka: 'skoda',
    model: 'octavia RS III',
    farba: 'cervena',
    palivo: 'benzin',
    vykon: 180,
    spotreba: 10,
    znamka: true,
    pozicane: true,
    cena: 80,
    popis:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce ipsum nunc, dictum vel dapibus at, luctus sit amet diam. Nam.',
  },
  {
    id: 6,
    spz: 'ZA483DS',
    img: '../img/06octavia-vrs-combi.png',
    znacka: 'skoda',
    model: 'octavia RS III combi',
    farba: 'strieborna',
    palivo: 'diesel',
    vykon: 130,
    spotreba: 6,
    znamka: true,
    pozicane: true,
    cena: 30,
    popis:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce ipsum nunc, dictum vel dapibus at, luctus sit amet diam. Nam.',
  },
  {
    id: 7,
    spz: 'ZA458LP',
    img: '../img/07passat2.png',
    znacka: 'volkswagen',
    model: 'passat',
    farba: 'strieborna',
    palivo: 'diesel',
    vykon: 90,
    spotreba: 5,
    znamka: true,
    pozicane: false,
    cena: 35,
    popis:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce ipsum nunc, dictum vel dapibus at, luctus sit amet diam. Nam.',
  },
  {
    id: 8,
    spz: 'ZA999AA',
    img: '../img/08skoda-superb-combi.png',
    znacka: 'skoda',
    model: 'superb combi',
    farba: 'biela',
    palivo: 'LPG',
    vykon: 110,
    spotreba: 11,
    znamka: false,
    pozicane: false,
    cena: 45,
    popis:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce ipsum nunc, dictum vel dapibus at, luctus sit amet diam. Nam.',
  },
  {
    id: 9,
    spz: 'BL963XF',
    img: '../img/09Superb-3.pngng',
    znacka: 'skoda',
    model: 'superb',
    farba: 'siva',
    palivo: 'benzin',
    vykon: 130,
    spotreba: 9,
    znamka: true,
    pozicane: false,
    cena: 35,
    popis:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce ipsum nunc, dictum vel dapibus at, luctus sit amet diam. Nam.',
  },
  {
    id: 10,
    spz: 'BL851MF',
    img: '../img/10tucson.png',
    znacka: 'hyundai',
    model: 'tucson',
    farba: 'modra',
    palivo: 'benzin',
    vykon: 130,
    spotreba: 12,
    znamka: true,
    pozicane: false,
    cena: 67,
    popis:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce ipsum nunc, dictum vel dapibus at, luctus sit amet diam. Nam.',
  },
];
